=== EPICSTools/ChannelArchiver/Engine/engineconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the ArchiveEngine Configuration           -->
<!-- Note that we do not allow empty configurations:   -->
<!-- Each config. must contain at least one group,     -->
<!-- and each group must cintain at least one channel. -->
<!ELEMENT engineconfig ((write_period|buffer_reserve)*,group+)>
<!ELEMENT group (name,channel+)>
<!ELEMENT channel (name,scan?,monitor?,disable?)>
<!ELEMENT write_period (#PCDATA)><!-- int "seconds" -->
<!ELEMENT buffer_reserve (#PCDATA)><!-- int "times"   -->
<!ELEMENT name (#PCDATA)>
<!ELEMENT scan (#PCDATA)><!-- double "seconds" -->
<!ELEMENT monitor EMPTY>
<!ELEMENT disable EMPTY>

=== EPICSTools/ChannelArchiver/Tools/test.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE engineconfig SYSTEM "../Engine/engineconfig.dtd">
<engineconfig>
   <write_period>30</write_period>
   <buffer_reserve>3</buffer_reserve>
   <group>
      <name>Vac</name>
      <channel><name>vac1</name><monitor/></channel>
      <channel><name>vac2</name><monitor/><disable/></channel>
      <channel><name>vac3</name><scan>30</scan></channel>
   </group>
   <group>
      <name>RF</name>
      <channel><name>rf1</name><monitor/></channel>
      <channel><name>rf2</name><monitor/></channel>
      <channel><name>rf3</name><scan>30</scan></channel>
   </group>
   <group>
      <name>Test</name>
      <channel><name>test1</name></channel>
   </group>
</engineconfig>
