=== EPICSTools/ChannelArchiver/ArchiveDaemon/ArchiveDaemon.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the ArchiveDaemon Configuration         -->
<!ELEMENT engines (engine+)>
<!ELEMENT engine (desc,port,config,daily?)>
<!ELEMENT desc (#PCDATA)>  <!-- Text -->
<!ELEMENT port (#PCDATA)>  <!-- TCP port number -->
<!ELEMENT config (#PCDATA)><!-- path -->
<!ELEMENT daily (#PCDATA)> <!-- HH:MM -->

=== EPICSTools/ChannelArchiver/ArchiveDaemon/ArchiveDaemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE engines SYSTEM "ArchiveDaemon.dtd">
<engines>
   <engine>
      <desc>Demo</desc>
      <port>4813</port>
      <config>/data/arch1/engineconfig.xml</config>
   </engine>
   <engine>
      <desc>Demo 2</desc>
      <port>4814</port>
      <config>/data/arch2/engineconfig.xml</config>
      <daily>02:00</daily>
   </engine>
</engines>

=== EPICSTools/ChannelArchiver/ExampleSetup/ArchiveDaemon.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE engines SYSTEM "ArchiveDaemon.dtd">
<engines>
   <engine>
      <desc>Demo</desc>
      <port>4813</port>
      <config>/arch/RF/llrf/llrf.xml</config>
   </engine>
   <engine>
      <desc>Demo 2</desc>
      <port>4814</port>
      <config>/arch/RF/hprf/hprf.xml</config>
      <daily>02:00</daily>
      <copy>dataserver:/arch/RF/hprf</copy>
   </engine>
</engines>
