=== EPICSTools/ChannelArchiver/ExampleSetup/archiveconfig.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!-- DTD for the archiveconfig -->
<!ELEMENT archiveconfig (daemon*)>

<!ELEMENT daemon (disable-check?,desc?,port,engine*)>
<!ATTLIST daemon directory CDATA #REQUIRED>

<!ELEMENT engine (disable-check?,desc?,port,restart?)>
<!ATTLIST engine directory CDATA #REQUIRED>

<!ELEMENT disable-check (#PCDATA)> <!-- true|false -->
<!ELEMENT desc (#PCDATA)>
<!ELEMENT port (#PCDATA)>

<!ELEMENT restart (#PCDATA)>
<!ATTLIST restart type CDATA #REQUIRED>

=== EPICSTools/ChannelArchiver/ExampleSetup/archiveconfig.xml
<?xml version="1.0" encoding="UTF-8" standalone="no"?>
<!DOCTYPE archiveconfig SYSTEM "archiveconfig.dtd">

<!-- Archive Configuration

     There is no DTD (yet),
     so try to avoid errors when editing this file.

  -->

<archiveconfig>

    <daemon directory='RF'>
        <desc>RF</desc>
        <port>4900</port>
        <engine directory='llrf'>
            <desc>LLRF</desc>
            <port>4901</port>
            <restart type='weekly'>We 10:20</restart>
        </engine>
        <engine directory='hprf'>
            <desc>HPRF</desc>
            <port>4902</port>
            <restart type='weekly'>We 10:30</restart>
        </engine>
    </daemon>

    <daemon directory='Test'>
        <desc>Test</desc>
        <port>4950</port>
        <engine directory='Test'>
            <desc>Test</desc>
            <port>4951</port>
            <restart type='daily'>08:00</restart>
        </engine>
    </daemon>
</archiveconfig>
